"""news

Revision ID: 0dd2a47388a1
Revises: b8e881d0433b
Create Date: 2026-01-07 23:55:10.014772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd2a47388a1'
down_revision: Union[str, None] = 'b8e881d0433b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('message_photo_file_id', sa.String(length=255), nullable=True))
    op.add_column('surveys', sa.Column('completion_photo_file_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'completion_photo_file_id')
    op.drop_column('surveys', 'message_photo_file_id')
    # ### end Alembic commands ###
