"""news

Revision ID: 31b7326c6ad4
Revises: 
Create Date: 2025-11-12 21:17:14.371251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b7326c6ad4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_days',
    sa.Column('day_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('day_id'),
    sa.UniqueConstraint('day_number')
    )
    op.create_table('settings',
    sa.Column('setting_key', sa.String(length=255), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('first_message_sent', sa.Boolean(), nullable=False),
    sa.Column('subscription_checked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_day', 'users', ['current_day'], unique=False)
    op.create_index('idx_user_subscribed', 'users', ['is_subscribed'], unique=False)
    op.create_table('schedule_posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_number'], ['schedule_days.day_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index('idx_post_day', 'schedule_posts', ['day_number'], unique=False)
    op.create_index('idx_post_delay', 'schedule_posts', ['delay_seconds'], unique=False)
    op.create_table('user_progress',
    sa.Column('progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['schedule_posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index('idx_progress_post', 'user_progress', ['post_id'], unique=False)
    op.create_index('idx_progress_user', 'user_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_progress_user', table_name='user_progress')
    op.drop_index('idx_progress_post', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('idx_post_delay', table_name='schedule_posts')
    op.drop_index('idx_post_day', table_name='schedule_posts')
    op.drop_table('schedule_posts')
    op.drop_index('idx_user_subscribed', table_name='users')
    op.drop_index('idx_user_day', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('schedule_days')
    # ### end Alembic commands ###
