"""news

Revision ID: 80152406e78b
Revises: 2a7e9c3d4f10
Create Date: 2026-01-14 19:16:46.852415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80152406e78b'
down_revision: Union[str, None] = '2a7e9c3d4f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('tgtrack_target', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'tgtrack_target')
    # ### end Alembic commands ###
